import localFont from "next/font/local";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {CommitmentProvider} from "@/lib/store/CommitmentContext";

const inter = localFont({
    src: "../fonts/Inter-VariableFont_opsz,wght.ttf",
    variable: "--font-inter",
    display: "swap",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
        <body>
        <CommitmentProvider>
            {children}
        </CommitmentProvider>
        </body>
        </html>
    );
}
