export const COMMITMENTS_LOADED = "COMMITMENTS_LOADED";
export const COMMITMENT_CREATED = "COMMITMENT_CREATED";
export const COMMITMENT_UPDATED = "COMMITMENT_UPDATED";
export const COMMITMENT_DELETED = "COMMITMENT_DELETED";
export const GOAL_TOGGLED = "GOAL_TOGGLED";
export const HABIT_STATUS_CHANGED = "HABIT_STATUS_CHANGED";

export const WIZARD_SET_FIELD = "WIZARD_SET_FIELD";
export const WIZARD_NEXT_STEP = "WIZARD_NEXT_STEP";
export const WIZARD_PREV_STEP = "WIZARD_PREV_STEP";
export const WIZARD_SET_MODE = "WIZARD_SET_MODE";
export const WIZARD_RESET = "WIZARD_RESET";
export const WIZARD_SET_ERRORS = "WIZARD_SET_ERRORS";
